version: "3"
services:
    elasticsearch:
        restart: always
        image: "elasticsearch:7.6.0"
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

    kibana:
        image: "kibana:7.6.0"
        restart: always
        ports:
            - "5601:5601"

    metricbeat:
        image: elastic/metricbeat:7.6.0
        restart: always
        user: root
        volumes:
            - ./config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
            - /proc:/hostfs/proc:ro
            - /:/hostfs:ro
                
        # disable strict permission checks
        command: ["--strict.perms=false", "-system.hostfs=/hostfs"]


volumes:
    elasticsearch_data:
