version: "3"
services:
    elasticsearch:
        restart: always
        image: "elasticsearch:7.6.1"
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

    kibana:
        image: "kibana:7.6.1"
        restart: always
        ports:
            - "5601:5601"

    logstash:
        image: "logstash:7.6.1"
        restart: always
        volumes:
            - type: bind
                source: ./config/logstash.yml
                target: /usr/share/logstash/config/logstash.yml
                read_only: true
            - type: bind
                source: ./config/pipeline
                target: /usr/share/logstash/pipeline
                read_only: true
        ports:
            - "9200:9200"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"        
        depends_on:
            - elasticsearch

volumes:
    elasticsearch_data:
