version: "3"
services:
    elasticsearch:
        restart: always
        image: "elasticsearch:7.6.0"
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

    kibana:
        image: "kibana:7.6.0"
        restart: always
        ports:
            - "5601:5601"


volumes:
    elasticsearch_data:
